package enums;

public enum Profissoes {
    AGRICULTOR, VENDEDOR, FERREIRO,
    MINERADOR, ASSASSINO, MERCENARIO,
    LADINO, PIRATA, ALQUIMISTA,
    MEDICO, MAGO, FEITICEIRO,
    ARQUEIRO, SOLDADO, DESEMPREGADO;
}